package name
import (. "github.com/less-leg/types"
"strings")
// This code was auto-generated by LOLSQL code-generation tool.
// Please do not modify it manually. All changes will be deleted after regeneration.
type column interface {Column() string}
type lol struct {
	selectColumns []column
	whereInited   bool
}

func (this *lol) Render() string {
	if (len(this.selectColumns) == 0) {
		return "select FIRST_NAME, SECOND_NAME, MIDDLE_NAME from Name"
	}
	cols := make([]string, 0, len(this.selectColumns))
	for _, selectColumn := range this.selectColumns {
		cols = append(cols, selectColumn.Column())
	}
	return "select " + strings.Join(cols, ", ") + " from Name"
}

func (this *lol) Where(cond LolCondition) *lolWhere {
	if this.whereInited {
		panic("Invalid usage of WHERE statement: double usage not supported.")
	}
	this.whereInited = true
	return &lolWhere{retrieval:this, condition:cond}
}

func Select(selects ...column) *lol {
	return &lol{selectColumns:selects}
}

type lolWhere struct {
	retrieval *lol
	condition LolCondition
	next      []LolCondition
}
func (this *lolWhere) Render() string {
	if len(this.next) > 0 {
		conds := make([]string, 0, len(this.next))
		for _, cond := range this.next {
			conds = append(conds, cond.Render())
		}
		return this.retrieval.Render() + " where (" + this.condition.Render() + ") " + strings.Join(conds, " ")
	}
	return this.retrieval.Render() + " where " + this.condition.Render()
}
func (this *lolWhere) And(cond LolCondition) *lolWhere {
	if this.next == nil {
		this.next = make([]LolCondition, 0, 1)
	}
	this.next = append(this.next, &lolConditionAnd{condition: cond})
	return this
}
func (this *lolWhere) Or(cond LolCondition) *lolWhere {
	if this.next == nil {
		this.next = make([]LolCondition, 0, 1)
	}
	this.next = append(this.next, &lolConditionOr{condition: cond})
	return this
}
type lolConditionAnd struct {
	HasNext
	condition LolCondition
}

func (this *lolConditionAnd) render() string {
	return "and (" + this.condition.Render() + ")"
}

func (this *lolConditionAnd) Render() string {
	if this.Next() != nil {
		return this.render() + " " + this.Next().Render()
	}
	return this.render()
}

func (this *lolConditionAnd) And(cond LolCondition) LolCondition {
	this.SetNext(&lolConditionAnd{condition:cond})
	return this
}

func (this *lolConditionAnd) Or(cond LolCondition) LolCondition {
	this.SetNext(&lolConditionOr{condition:cond})
	return this
}
type lolConditionOr struct {
	HasNext
	condition LolCondition
}
func (this *lolConditionOr) render() string {
	return "or (" + this.condition.Render() + ")"
}
func (this *lolConditionOr) Render() string {
	if this.Next() != nil {
		return this.render() + " " + this.Next().Render()
	}
	return this.render()
}
func (this *lolConditionOr) And(cond LolCondition) LolCondition {
	this.SetNext(&lolConditionAnd{condition:cond})
	return this
}
func (this *lolConditionOr) Or(cond LolCondition) LolCondition {
	this.SetNext(&lolConditionOr{condition:cond})
	return this
}

type MiddleNameStub struct { column }
var MiddleNameStubConst MiddleNameStub
func MiddleName() *MiddleNameStub {return &MiddleNameStubConst}
func (*MiddleNameStub) Column() string {return "MiddleName"}

type FirstNameStub struct { column }
var FirstNameStubConst FirstNameStub
func FirstName() *FirstNameStub {return &FirstNameStubConst}
func (*FirstNameStub) Column() string {return "FirstName"}

type SecondNameStub struct { column }
var SecondNameStubConst SecondNameStub
func SecondName() *SecondNameStub {return &SecondNameStubConst}
func (*SecondNameStub) Column() string {return "SecondName"}

